version: "2.0"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./ui:/var/www/ui
      - ./api:/var/www/api
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php-fpm-pgsql:latest
    build: ./docker-php-fpm-pgsql
    volumes:
      - .:/var/www/html
    links:
      - pgsql

  pgsql:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    external:
      name: dbdata
